name: Livecode (Code Sanity Check & Test)

on: [ push, pull_request ]

jobs:
  sanity_check:
    runs-on: ubuntu-latest
    name: Sanity Check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 -q
      - name: Running Sanity Check
        run: |
          flake8

  test:
    runs-on: ubuntu-latest
    name: Test Cases
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt -q
      - name: Running Tests
        run: |
          make setup
          PYTHONPATH=. pytest -v tests/ $*
